
; ═══ SYSTEM SHORTCUTS ═════════════════════════════════════════════════════════

; Ctrl+Alt+Win+ñ — Reload the script via the upkey shell command
^#!ñ::
{
    MsgBox("Script reloaded!", "Success", "Iconi T1")
    Run('pwsh.exe -NoLogo -Command ". $PROFILE; upkey"')
}

; Ctrl+Alt+Win+p — Open the splice sources folder (this file is generated by merge.py)
^#!p::
{
    LaunchAndFocus('C:\Windows\explorer.exe', '"' A_ScriptDir '\src"')
}

; Win+E — Open Downloads in File Explorer
#e::
{
    LaunchAndFocus('C:\Windows\explorer.exe', '"C:\Users\Leonardo\Downloads"')
}

; Ctrl+Win+T — Launch Windows Terminal
^#t:: {
    LaunchAndFocus(EnvGet("LOCALAPPDATA") . "\Microsoft\WindowsApps\wt.exe", "", "WindowsTerminal.exe")
}

; Ctrl+Alt+Shift+Win (all combos) — Block Office/M365 global intercept.
; Prevents the key combo from launching m365.cloud.microsoft on release.
#^!Shift::
#^+Alt::
#!+Ctrl::
^!+LWin:: {
    Send("{Blind}{vk07}")
}

; Ctrl+Alt+Win+Left — Previous media track
^#!Left:: {
    Send("{Media_Prev}")
}

; Ctrl+Alt+Win+Right — Next media track
^#!Right:: {
    Send("{Media_Next}")
}

; Ctrl+Alt+Win+Up — Volume up by 1
^#!Up:: {
    SoundSetVolume("+1")
}

; Ctrl+Alt+Win+Down — Volume down by 1
^#!Down:: {
    SoundSetVolume("-1")
}
